apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amitopenwriteup/argocdproj.git'
    targetRevision: amit
    path: proj
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: amit-microservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

